Feature/post card
felipegoulart/quasar-blog pull request #2
Opened 2021-11-12 14:36 UTC by felipegoulart

2021-11-12 16:52 UTC, felipegoulart commented on src/components/ModalDelete.vue
> +        <q-btn flat label="Cancelar" color="dark" @click="isOpened = false"/>
Mesmo para uma lógica simples?

2021-11-12 16:52 UTC, felipegoulart commented on src/components/ModalDelete.vue
> +      <q-card-actions align="right">
Mas se ele é especifico para delete, por que fazer um slot para as actions?

2021-11-12 16:54 UTC, felipegoulart commented on src/components/PostCard.vue
> +        <q-fab-action @click="editPost" color="white" icon="edit" label="Editar Post" text-color="gray-10"/>
Além da ordenação alfabética ele deve levar algo a mais em consideração?

2021-11-12 16:56 UTC, felipegoulart commented on src/pages/PostForm.vue
> +<script>
Essa ainda está em construção, por isso ainda tem o script. Se não tiver enganado o script é obrigatório no ```.vue```

2021-11-12 16:56 UTC, DouglasCalora commented on src/components/ModalDelete.vue
> +        <q-btn flat label="Cancelar" color="dark" @click="isOpened = false"/>
Crie um metodo `toggleModal`

2021-11-12 16:56 UTC, DouglasCalora commented on src/components/ModalDelete.vue
> +        <q-btn flat label="Deletar" color="negative" @click="deleteItem"/>
faltou um espaço antes do `/>`

2021-11-12 16:56 UTC, DouglasCalora commented on package.json
> +    "date-fns": "^2.25.0",
Porque precisou instalar uma lib para essas datas? Chegou a olhar os helpers de datas que o proprio quasar disponibiliza?

2021-11-12 16:56 UTC, DouglasCalora commented on src/components/PostCard.vue
> +      <router-link class="post-card__link" to="">Ver mais</router-link>
Porque ta usando um router-link?

2021-11-12 16:56 UTC, DouglasCalora commented on src/components/PostCard.vue
> +      opened: false
pq não esta usando `isOpened` aqui?

2021-11-12 16:56 UTC, DouglasCalora commented on src/components/PostCard.vue
> +    editPost () {
algo comoo `goToEdit` não ficar melhor?

2021-11-12 16:56 UTC, DouglasCalora commented on src/components/PostCard.vue
> +      console.log('Esse post será removido em algum momento')
remover console.log

2021-11-12 16:56 UTC, DouglasCalora commented on src/components/PostCard.vue
> +
muito desses atributos css existem como classe utilitaria no quasar, eu exploraria elas

2021-11-12 16:56 UTC, DouglasCalora commented on src/pages/Index.vue
> +        'creation-date': new Date()
Este atributo é normalmente chamado de `createdAt` e usado o padrão iso com `toISOString()`

2021-11-12 16:56 UTC, felipegoulart commented on src/router/routes.js
> +      { path: 'new', name: 'newPost', component: () => import('pages/PostForm.vue'), meta: { edit: false } },
Boa. Vou ajustar

2021-11-12 17:16 UTC, felipegoulart commented on package.json
> +    "date-fns": "^2.25.0",
Não tinha visto os helpers, vou verificar e faço a alteração.

2021-11-12 17:17 UTC, felipegoulart commented on src/components/PostCard.vue
> +      <router-link class="post-card__link" to="">Ver mais</router-link>
Vou redirecionar para uma outra tela, a "postSingle", que ainda não está pronta

2021-11-12 17:17 UTC, felipegoulart commented on src/components/PostCard.vue
> +    editPost () {
Fiz assim inicialmente, mas não sabia se era o mais adequado.

2021-11-12 17:19 UTC, felipegoulart commented on src/components/PostCard.vue
> +
O card precisa ser feito manualmente, o restante poderá ser feito com o Quasar.

2021-11-12 19:08 UTC, felipegoulart commented on src/components/ModalDelete.vue
> +      <q-card-actions align="right">
Decidido por manter como está

2021-11-12 19:10 UTC, felipegoulart commented on src/components/PostCard.vue
> +      <p class="post-card__description">
Não entendi

2021-11-12 19:34 UTC, felipegoulart commented on src/components/PostCard.vue
> +      return format(this.post['creation-date'], "dd 'de' MMM yyyy", { locale: ptBR })
Substitui pelo helper do Quasar

2021-11-12 19:34 UTC, felipegoulart commented on src/components/PostCard.vue
> +
Feito

2021-11-12 19:35 UTC, felipegoulart commented on src/pages/Index.vue
> +  components: {
Feito

2021-11-12 19:35 UTC, felipegoulart commented on src/pages/Index.vue
> +import PostCard from 'src/components/PostCard'
Feito

2021-11-12 19:35 UTC, felipegoulart commented on src/pages/PostForm.vue
> +<style>
Feito

2021-11-12 19:37 UTC, felipegoulart commented on src/components/PostCard.vue
> +      <router-link class="post-card__link" to="">Ver mais</router-link>
Feito

2021-11-12 19:37 UTC, felipegoulart commented on src/components/PostCard.vue
> +      opened: false
Esqueci de fazer as alterações

2021-11-12 19:38 UTC, felipegoulart commented on src/components/PostCard.vue
> +    editPost () {
Feito

2021-11-12 19:38 UTC, felipegoulart commented on src/components/PostCard.vue
> +      console.log('Esse post será removido em algum momento')
Função removida

2021-11-12 20:15 UTC, eliasassuncao requested changes

2021-11-12 20:15 UTC, eliasassuncao commented on src/components/PostCard.vue
> +      <p class="post-card__description">
`<p class="post-card__description">{{ post.description }}</p>`

2021-11-12 20:15 UTC, eliasassuncao commented on src/pages/PostForm.vue
> +<script>
ok, mantem só com o name msm

2021-11-12 20:22 UTC, felipegoulart reviewed
Feito

2021-11-12 20:48 UTC, eliasassuncao requested changes

2021-11-12 20:48 UTC, eliasassuncao commented on src/components/PostCard.vue
> +      return date.formatDate(this.post.createdAt, 'DD-MM-YYYY')
poderia ser um helper não?

2021-11-12 20:48 UTC, eliasassuncao commented on src/router/routes.js
> +        path: 'new',
path ainda não segue o padrão. o do edit tbm

2021-11-12 20:51 UTC, felipegoulart commented on src/components/PostCard.vue
> +      return date.formatDate(this.post.createdAt, 'DD-MM-YYYY')
Pensando que utilizarei em mais de um ponto, pode ser uma boa.

2021-11-16 13:49 UTC, felipegoulart commented on src/router/routes.js
> +        path: 'new',
Feito

2021-11-16 14:00 UTC, eliasassuncao commented on src/router/routes.js
> +        component: () => import('pages/PostForm.vue'),
deveria ser `PostsForm`

2021-11-16 14:02 UTC, felipegoulart commented on src/router/routes.js
> +        component: () => import('pages/PostSingle.vue')
Mesmo que seja para um único item devo colocar no plural?

2021-11-16 14:03 UTC, felipegoulart commented on src/router/routes.js
> +        component: () => import('src/pages/PostList.vue')
Feito

2021-11-16 14:08 UTC, eliasassuncao commented on src/router/routes.js
> +        component: () => import('pages/PostSingle.vue')
sim, nosso padrão é `nome da entidade + ação`
```
entidade services:

/services - listagem
/services/new - criação
/services/:id/edit - edição
/services/:id - visualização

```

2021-11-16 14:22 UTC, felipegoulart commented on src/router/routes.js
> +        component: () => import('pages/PostSingle.vue')
Sim, isso eu entendi, me refiro o nome no plural como servicesSingle em vez de serviceSingle

2021-11-16 14:23 UTC, felipegoulart commented on src/router/routes.js
> +        component: () => import('pages/PostForm.vue'),
Feito

2021-11-16 14:23 UTC, felipegoulart commented on src/components/PostCard.vue
> +      <router-link class="post-card__link" :to="{name: 'postEdit', params: { id: post.id } }">Ver mais</router-link>
Feito

2021-11-16 14:27 UTC, felipegoulart commented on src/helpers/date.js
> +  formatDefault (value) {
Faz mais sentido dessa forma, a função fica mais genérica e reutilizável.

2021-11-16 18:18 UTC, eliasassuncao approved these changes

2021-11-16 18:21 UTC, merged