Feature/posts request
felipegoulart/quasar-blog pull request #5
Opened 2021-11-18 14:31 UTC by felipegoulart

2021-11-18 15:05 UTC, eliasassuncao requested changes

2021-11-18 15:05 UTC, eliasassuncao commented on src/pages/PostsSingle.vue
> +      return date.formatDate(this.post.createdAt)
- poderia passar direto na view.
- acho q está errado a forma q vc exporta lá no `index` dos helpers, pq vc deveria estar utilizando diretamente o `formatDate` e não `date.formatDate`

2021-11-18 15:05 UTC, eliasassuncao commented on src/pages/PostsSingle.vue
> +      return date.formatDate(this.post.updatedAt)
o mesmo aqui

2021-11-18 15:05 UTC, eliasassuncao commented on src/store/modules/posts.js
> +  },
quebrar linha

2021-11-18 15:05 UTC, eliasassuncao commented on src/store/modules/posts.js
> +  getters: {},
quebrar linha

2021-11-18 15:05 UTC, eliasassuncao commented on src/store/modules/posts.js
> +  },
quebrar linha

2021-11-18 15:05 UTC, eliasassuncao commented on src/store/modules/posts.js
> +        const data = (await services.posts.list()).data
`const { data } = await services.posts.list()`

2021-11-18 15:05 UTC, eliasassuncao commented on src/store/modules/posts.js
> +        const data = (await services.posts.single(payload)).data
`const { data } = await services.posts.single(payload)`

2021-11-18 15:05 UTC, eliasassuncao commented on src/store/modules/posts.js
> +        console.log(err)
não seria melhor colocar um  notify?

2021-11-18 15:05 UTC, eliasassuncao commented on src/store/modules/posts.js
> +        console.log(err)
não seria melhor colocar um  notify?

2021-11-18 15:05 UTC, eliasassuncao commented on src/pages/PostsSingle.vue
> +      default: null,
default tem q ser uma string vazia por conta do type

2021-11-18 15:05 UTC, eliasassuncao commented on src/pages/PostsList.vue
> +    ...mapActions('posts', ['listPosts'])
seria `postsList` não?

2021-11-18 16:09 UTC, felipegoulart commented on src/store/modules/posts.js
> +        const data = (await services.posts.list()).data
Boa. Não tinha pensado em fazer desta forma

2021-11-18 16:09 UTC, felipegoulart commented on src/store/modules/posts.js
> +        const data = (await services.posts.single(payload)).data
O mesmo aqui

2021-11-18 16:10 UTC, felipegoulart commented on src/pages/PostsList.vue
> +    ...mapActions('posts', ['listPosts'])
Estou com dúvida da nomenclatura das actions

2021-11-18 16:11 UTC, felipegoulart commented on src/store/modules/posts.js
> +  getters: {},
```suggestion
  getters: {
  },
````  ?

2021-11-18 17:36 UTC, felipegoulart commented on src/pages/PostsSingle.vue
> +      return date.formatDate(this.post.createdAt)
Eu importava tudo para index e exportava de lá. Olhei no projeto do SAD e vi que importam direto do arquivo por isso da diferença.
A forma que fazem é menos verbosa, então adotei ela

2021-11-18 17:36 UTC, felipegoulart commented on src/pages/PostsSingle.vue
> +      return date.formatDate(this.post.updatedAt)
feito

2021-11-18 17:37 UTC, felipegoulart commented on src/pages/PostsSingle.vue
> +      default: null,
Feito

2021-11-18 17:38 UTC, felipegoulart commented on src/store/modules/posts.js
> +        console.log(err)
Vou dar uma olhada no componente

2021-11-19 21:42 UTC, eliasassuncao requested changes

2021-11-19 21:42 UTC, eliasassuncao commented on quasar.conf.js
> +      config: { notify: { /* look at QUASARCONFOPTIONS from the API card (bottom of page) */ } },
acho q não precisa dessa config

2021-11-19 21:42 UTC, eliasassuncao commented on src/components/PostCard.vue
> +      return formatDate(this.post.createdAt)
poderia usar essa função direta não?

2021-11-19 21:42 UTC, eliasassuncao commented on src/components/PostCard.vue
> +        console.log(err)
remover console.log

2021-11-19 21:42 UTC, eliasassuncao commented on src/components/PostCard.vue
> +    toggleRemovePost () {
`handleModalDelete` não ficaria melhor?

2021-11-19 21:42 UTC, eliasassuncao commented on src/pages/PostsForm.vue
> +    ...mapActions('posts', ['createPost', 'editPost', 'fetchPost', 'fetchCategories', 'fetchAuthors', 'removePost']),
quebrar esses arrays por linha

2021-11-19 21:42 UTC, eliasassuncao commented on src/pages/PostsForm.vue
> +      this.localPost = { ...newValue }
qual o motivo desse watch?

2021-11-19 21:42 UTC, eliasassuncao commented on src/pages/PostsForm.vue
> +        } catch (err) {
remover parametro `err` q não esta sendo utilizado

2021-11-19 21:42 UTC, eliasassuncao commented on src/pages/PostsForm.vue
> +      } else {
esse if else não deveria ser somente pra as actions? ai não precisaria dar copy paste nos notify

2021-11-19 21:42 UTC, eliasassuncao commented on src/pages/PostsForm.vue
> +      } catch (err) {
remover parametro `err` não utilizadi

2021-11-19 21:42 UTC, eliasassuncao commented on src/pages/PostsForm.vue
> +      return checkEmptyValue(value, 'Digite uma descrição')
poderia passar o helper diretamente na view

2021-11-19 21:42 UTC, eliasassuncao commented on src/pages/PostsForm.vue
> +      return urlValidator(value, 'Digite um link válido')
poderia passar o helper diretamente na view

2021-11-19 21:42 UTC, eliasassuncao commented on src/pages/PostsForm.vue
> +      return checkEmptyValue(value, 'Digite um título')
poderia passar o helper diretamente na view

2021-11-19 21:42 UTC, eliasassuncao commented on src/pages/PostsSingle.vue
> +    updatedAt () {
poderia passar direto na view

2021-11-19 21:42 UTC, eliasassuncao commented on src/pages/PostsSingle.vue
> +      return formatDate(this.post.createdAt)
poderia passar direto na view

2021-11-19 21:42 UTC, eliasassuncao commented on src/services/authors.js
> +    return axios.get('authors')
o try catch fica onde?

2021-11-19 21:42 UTC, eliasassuncao commented on src/services/categories.js
> +    return axios.get('categories')
o try catch fica onde?

2021-11-19 21:42 UTC, eliasassuncao commented on src/services/posts.js
> +    return axios.get('posts')
o try catch fica onde?

2021-11-19 21:42 UTC, eliasassuncao commented on src/services/posts.js
> +    return axios.get(`posts/${id}`)
o try catch fica onde?

2021-11-19 21:42 UTC, eliasassuncao commented on src/services/posts.js
> +    return axios.post('posts', { ...body })
o try catch fica onde?

2021-11-19 21:42 UTC, eliasassuncao commented on src/services/posts.js
> +    return axios.put(`posts/${id}`, { ...body })
o try catch fica onde?

2021-11-19 21:42 UTC, eliasassuncao commented on src/services/posts.js
> +    return axios.delete(`posts/${id}`)
o try catch fica onde?

2021-11-19 21:42 UTC, eliasassuncao commented on src/store/modules/posts.js
> +      } catch (err) {
remover parametro `err` não usado

2021-11-19 21:42 UTC, eliasassuncao commented on src/store/modules/posts.js
> +      } catch (err) {
remover parametro `err` não usado

2021-11-19 21:42 UTC, eliasassuncao commented on src/store/modules/posts.js
> +      } catch (err) {
remover parametro `err` não usado

2021-11-19 21:42 UTC, eliasassuncao commented on src/store/modules/posts.js
> +        console.log(err)
vai ter um notify? se não, remover `err`

2021-11-19 21:42 UTC, eliasassuncao commented on src/store/modules/posts.js
> +      } catch (err) {
remover `err` não usado

2021-11-19 21:42 UTC, eliasassuncao commented on src/store/modules/posts.js
> +        console.log(err)
remover console.log

2021-11-19 21:42 UTC, eliasassuncao commented on src/store/modules/posts.js
> +      await services.posts.edit(id, body)
precisa de um try catch não?

2021-11-19 21:42 UTC, eliasassuncao commented on src/store/modules/posts.js
> +      await services.posts.remove(payload)
precisa de um try catch não?

2021-11-19 21:42 UTC, eliasassuncao commented on src/pages/PostsForm.vue
> +      if (this.isEdit) return this.$route?.params?.id
poderia utilizar `this.isEdit && this.$route?.params?.id`

2021-11-19 21:42 UTC, eliasassuncao commented on src/pages/PostsForm.vue
> +      localPost: {
poderia ser `values` não?

2021-11-22 12:10 UTC, felipegoulart commented on src/components/PostCard.vue
> +      return formatDate(this.post.createdAt)
Como referencio uma função importada no template?

2021-11-22 12:12 UTC, felipegoulart commented on src/components/PostCard.vue
> +    toggleRemovePost () {
Por ele estar habilitando e desabilitando o toggle faz mais sentido para mim. 
Vejo o handler mais como um manipulador de dados

2021-11-22 12:12 UTC, felipegoulart commented on src/pages/PostsForm.vue
> +    ...mapActions('posts', ['createPost', 'editPost', 'fetchPost', 'fetchCategories', 'fetchAuthors', 'removePost']),
Feito

2021-11-22 12:32 UTC, felipegoulart commented on src/pages/PostsForm.vue
> +      this.localPost = { ...newValue }
A intenção era de assim que o `state` fosse alterado ele passaria o valor para o `localPost`

2021-11-22 12:35 UTC, felipegoulart commented on src/pages/PostsForm.vue
> +        } catch (err) {
É obrigatório passar um parâmetro para erro quando se faz `try catch`. Ideal é que eu faça algo com esse `err`, só não sei como.

2021-11-22 12:37 UTC, felipegoulart commented on src/pages/PostsForm.vue
> +      } else {
Faz sentido. Vou fazer as modificações

2021-11-22 13:01 UTC, felipegoulart commented on quasar.conf.js
> +      config: { notify: { /* look at QUASARCONFOPTIONS from the API card (bottom of page) */ } },
Feito

2021-11-22 13:14 UTC, felipegoulart commented on src/components/PostCard.vue
> +      return formatDate(this.post.createdAt)
Feito

2021-11-22 13:14 UTC, felipegoulart commented on src/components/PostCard.vue
> +        console.log(err)
feito

2021-11-22 13:15 UTC, felipegoulart commented on src/pages/PostsForm.vue
> +        } catch (err) {
Removi esse `try catch` do componente.

2021-11-22 13:18 UTC, felipegoulart commented on src/pages/PostsForm.vue
> +      } catch (err) {
Feito

2021-11-22 13:54 UTC, felipegoulart commented on src/pages/PostsForm.vue
> +      return checkEmptyValue(value, 'Digite uma descrição')
Feito

2021-11-22 13:54 UTC, felipegoulart commented on src/pages/PostsForm.vue
> +      return urlValidator(value, 'Digite um link válido')
Feito

2021-11-22 14:02 UTC, felipegoulart commented on src/pages/PostsForm.vue
> +      return checkEmptyValue(value, 'Digite um título')
Feito

2021-11-22 14:04 UTC, felipegoulart commented on src/pages/PostsSingle.vue
> +    updatedAt () {
Feito

2021-11-22 14:04 UTC, felipegoulart commented on src/pages/PostsSingle.vue
> +      return formatDate(this.post.createdAt)
Feito

2021-11-22 14:07 UTC, felipegoulart commented on src/services/authors.js
> +    return axios.get('authors')
Na Action

2021-11-22 14:07 UTC, felipegoulart commented on src/services/categories.js
> +    return axios.get('categories')
Na Action

2021-11-22 14:07 UTC, felipegoulart commented on src/services/posts.js
> +    return axios.get('posts')
Na Action

2021-11-22 14:07 UTC, felipegoulart commented on src/services/posts.js
> +    return axios.post('posts', { ...body })
Na Action

2021-11-22 14:07 UTC, felipegoulart commented on src/services/posts.js
> +    return axios.get(`posts/${id}`)
Na Action

2021-11-22 14:07 UTC, felipegoulart commented on src/services/posts.js
> +    return axios.put(`posts/${id}`, { ...body })
Na Action

2021-11-22 14:07 UTC, felipegoulart commented on src/services/posts.js
> +    return axios.delete(`posts/${id}`)
Na Action

2021-11-22 14:07 UTC, felipegoulart commented on src/store/modules/posts.js
> +      } catch (err) {
Feito

2021-11-22 14:08 UTC, felipegoulart commented on src/store/modules/posts.js
> +      } catch (err) {
Feito

2021-11-22 14:08 UTC, felipegoulart commented on src/store/modules/posts.js
> +      } catch (err) {
Feito

2021-11-22 14:08 UTC, felipegoulart commented on src/store/modules/posts.js
> +        console.log(err)
Feito

2021-11-22 14:08 UTC, felipegoulart commented on src/store/modules/posts.js
> +      } catch (err) {
Feito

2021-11-22 14:08 UTC, felipegoulart commented on src/store/modules/posts.js
> +        console.log(err)
Feito

2021-11-22 14:08 UTC, felipegoulart commented on src/store/modules/posts.js
> +      await services.posts.edit(id, body)
Feito

2021-11-22 14:09 UTC, felipegoulart commented on src/store/modules/posts.js
> +      await services.posts.remove(payload)
Feito

2021-11-22 14:09 UTC, felipegoulart commented on src/pages/PostsForm.vue
> +      if (this.isEdit) return this.$route?.params?.id
Qual você acredita ser melhor para entender?

2021-11-22 14:10 UTC, felipegoulart commented on src/pages/PostsForm.vue
> +      localPost: {
`localPost` ser `values: {}`?

2021-11-22 14:37 UTC, eliasassuncao commented on src/pages/PostsForm.vue
> +      localPost: {
isso

2021-11-22 14:47 UTC, felipegoulart commented on src/pages/PostsForm.vue
> +      localPost: {
Perfeito. vou alterar

2021-11-22 14:48 UTC, eliasassuncao requested changes

2021-11-22 14:48 UTC, eliasassuncao commented on src/components/PostCard.vue
> +    toggleRemovePost () {
ok

2021-11-22 14:48 UTC, eliasassuncao commented on src/components/PostCard.vue
> +      } catch (err) {
remover `(err)` não usado

2021-11-22 14:48 UTC, eliasassuncao commented on src/pages/PostsForm.vue
> +    <q-input v-model="localPost.title" class="q-my-sm" filled label="Título" :rules="[checkEmptyValue || 'Digite um título']" />
poderia isolar o message no helper
```
export function checkEmptyValue (value, message = 'Campo obrigatório') {
  return !!value.trim().length || message
}

export function urlValidator (value, message = 'Campo obrigatório') {
  const regex = /^https?:\/\/([a-z]+)/
  return regex.test(value) || message
}

:rules="[value => checkEmptyValue(value,  'Digite um título')]"

```

2021-11-22 14:48 UTC, eliasassuncao commented on src/pages/PostsForm.vue
> +    <q-input v-model="localPost.image" class="q-my-sm" filled label="Imagem (URL)" :rules="[urlValidator || 'Digite uma URL válida']" />
utilizar o mesmo exemplo pra os outros rules

2021-11-22 14:48 UTC, eliasassuncao commented on src/pages/PostsList.vue
> +      <post-card :post="post" @update-status="fetchPostsList" />
oq seria esse `update-status` ?

2021-11-22 14:48 UTC, eliasassuncao commented on src/pages/PostsSingle.vue
> +    formatDate
deveria ser um method não?

2021-11-22 14:48 UTC, eliasassuncao commented on src/services/categories.js
> +    return axios.get('categories')
ok

2021-11-22 14:48 UTC, eliasassuncao commented on src/services/posts.js
> +    return axios.get(`posts/${id}`)
ok

2021-11-22 14:48 UTC, eliasassuncao commented on src/services/posts.js
> +    return axios.put(`posts/${id}`, { ...body })
ok

2021-11-22 14:48 UTC, eliasassuncao commented on src/services/posts.js
> +    return axios.delete(`posts/${id}`)
ok

2021-11-22 14:48 UTC, eliasassuncao commented on src/store/modules/posts.js
> +        isEdit ? dispatch('editPost', post) : dispatch('createPost', post)
uma outra forma seria `dispatch(isEdit ? 'editPost' : 'createPost', post)`

2021-11-22 14:48 UTC, eliasassuncao commented on src/store/modules/posts.js
> +        throw new Error('Falha na requisição')
existe outro try catch onde vc usa esse `submitPost` ? se não tiver vai crashar

2021-11-22 14:52 UTC, felipegoulart commented on src/pages/PostsForm.vue
> +      if (this.isEdit) return this.$route?.params?.id
Então vou alterar

2021-11-22 15:03 UTC, felipegoulart commented on src/pages/PostsForm.vue
> +    <q-input v-model="localPost.title" class="q-my-sm" filled label="Título" :rules="[checkEmptyValue || 'Digite um título']" />
Entendi. Estava com dificuldade em usar o rules com uma função e passar o valor. Agora ficou mais claro de como fazer

2021-11-22 15:04 UTC, felipegoulart commented on src/pages/PostsForm.vue
> +    <q-input v-model="localPost.image" class="q-my-sm" filled label="Imagem (URL)" :rules="[urlValidator || 'Digite uma URL válida']" />
Feito

2021-11-22 15:04 UTC, felipegoulart commented on src/pages/PostsSingle.vue
> +    formatDate
Sim, foi falta de atenção minha!

2021-11-22 15:07 UTC, felipegoulart commented on src/store/modules/posts.js
> +        isEdit ? dispatch('editPost', post) : dispatch('createPost', post)
É uma forma abreviada, mas pode causar confusão se não estiver atento. Apesar de os dois `dispatch` ser repetitivo, ele é mais claro da sua função.

2021-11-22 15:07 UTC, felipegoulart commented on src/store/modules/posts.js
> +        throw new Error('Falha na requisição')
Verdade, não pensei nisto. Vou remover

2021-11-22 15:09 UTC, felipegoulart commented on src/pages/PostsList.vue
> +      <post-card :post="post" @update-status="fetchPostsList" />
Quando o card realizar alguma ação que precisa ser escutada pelo elemento Pai, será feito por este listener.
ex: O card foi removido na listagem e a postList precisa atualizar a página, ele escutará por aí

2021-11-22 17:52 UTC, felipegoulart commented on src/pages/PostsList.vue
> +      <post-card :post="post" @update-status="fetchPostsList" />
Alterada a forma de atualizar a lista

2021-11-22 19:35 UTC, eliasassuncao approved these changes

2021-11-22 19:35 UTC, eliasassuncao commented on src/components/PostCard.vue
> +    ...mapMutations('posts', ['postsMutation']),
- quebrar linha pra separar do `mapActions`
- não costumamos utilizar mutations diretamente, sempre utilizar uma action

2021-11-22 20:28 UTC, eliasassuncao approved these changes

2021-11-22 20:29 UTC, merged